# Default values for example-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  # change image to generate chart
  #repository: dvk16/helm-intro
  repository: dvk16/go-app
  tag: latest
  pullPolicy: Always
service:
  name: example-app
  externalPort: 80
  internalPort: 5000
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    kubernetes.io/ingress.class: example-app
    kubernetes.io/tls-acme: "true"
  tls:
    - secretName: chart-example-tls
      hosts:
       - chart-example.local
resources: {}
